catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig

from catalog.views import (display_contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, PostListView, PostDetailView, PostCreateView, PostUpdateView,
                           PostDeleteView)

app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),

    path('contacts/', display_contacts, name='contacts'),

    path('blog/', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/<str:slug>/', PostDetailView.as_view(), name='post'),
    path('post/update/<int:pk>/<str:slug>', PostUpdateView.as_view(), name='update_post'),
    path('post/delete/<int:pk>/<str:slug>', PostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_user, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/<int:user_pk>/', verification_user, name='verification'),
    # path('recovery_password/', PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='recovery_password'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password')
]

catalog/models.py
from django.db import models
from pytils.translit import slugify

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.CharField(max_length=100)
    price = models.IntegerField(verbose_name='цена за покупку')
    date_of_creation = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    date_of_change = models.DateTimeField(verbose_name='дата последнего изменения', auto_now=True)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Кем создан', **NULLABLE)

    def __str__(self):
        return f'{self.title} - {self.price} рублей'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('title',)


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('title',)


class Post(models.Model):
    name = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    published = models.BooleanField(verbose_name='признак публикации', default=True)
    views_count = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.slug is None:
            self.slug = slugify(self.name)

    def __str__(self):
        return f'{self.name} {self.slug}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created_at',)

    def increase_views_count(self):
        """
        Увеличивает просмотры поста на 1.
        """
        self.views_count += 1
        self.save()


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.IntegerField(verbose_name='номер версии')
    title_version = models.CharField(max_length=150, verbose_name='название версии')
    is_active = models.BooleanField(verbose_name='признак текущей версии', default=True)

    def __str__(self):
        return f'{self.title_version} ({self.product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleForMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleForMixin, forms.ModelForm):

    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                       'радар']

    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'category', 'price')

    def clean_title(self):
        clean_title = self.cleaned_data['title']
        for word in self.forbidden_words:
            if word in clean_title.lower():
                raise forms.ValidationError(f'Название не может содержать слово "{word}"')
        return clean_title

    def clean_description(self):
        clean_description = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in clean_description.lower():
                raise forms.ValidationError(f'Описание не может содержать слово "{word}"')
        return clean_description


class VersionForm(StyleForMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Post, Version


class ProductListView(ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


def display_contacts(request):
    return render(request, 'catalog/contacts.html')


class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = Post.objects.filter(published=True)
        return queryset


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        post.increase_views_count()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ('name', 'content', 'image', 'published')
    success_url = reverse_lazy('catalog:post_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.name)
            new_post.save()
            return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ('name', 'content', 'image', 'published')
    # success_url = reverse_lazy('catalog:post_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.name)
            new_post.save()

            return super().form_valid(form)

    def get_success_url(self):

        return reverse('catalog:post', args=[self.kwargs.get('pk'), self.kwargs.get('slug')])


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('catalog:post_list')

catalog/templates/catalog/includes/inc_catalog_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

catalog/templates/catalog/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

catalog/templates/catalog/includes/inc_post_card.html
{% load mediapath %}

<div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-2 font-weight-normal">{{object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{object.content|truncatechars:150}}</li>
                        </ul>
                        <p><img src="{% mediapath object.image %}" width="150" height="120" alt="Картинка"></p>
                        <p><a class="btn btn-secondary" href="{% url 'catalog:post' object.pk object.slug  %}" role="button">Посмотреть &raquo;</a></p>
                        <p><a class="btn btn-warning" href="{% url 'catalog:update_post' object.pk object.slug %}" role="button">Изменить &raquo;</a></p>
                        <p><a class="btn btn-danger" href="{% url 'catalog:delete_post' object.pk object.slug %}" role="button">Удалить &raquo;</a></p>


                    </div>
                </div>
            </div>

catalog/templates/catalog/includes/inc_product.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Наименование</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td>Изображение</td>
                        <td>{{ object.image }}</td>
                    </tr>
                    <tr>
                        <td>Цена</td>
                        <td>{{ object.price }}</td>
                    </tr>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/includes/inc_product_card.html
{% load mediapath %}

<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h3 class="my-2 font-weight-normal">{{object.title}}</h3>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{object.description|truncatechars:100}}</li>
            </ul>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                {% for version in object.version_set.all %}
                {% if version.is_active %}

                <div><strong>Активная версия: </strong> {{ version.number_version}} - {{ version.title_version}}</div>
                {% endif %}
                {% endfor %}

            </ul>

            <p><img src="{% mediapath object.image %}" width="150" height="120" alt="Картинка"></p>
            <p><a class="btn btn-secondary" href="{% url 'catalog:product' object.pk %}" role="button">Посмотреть &raquo;</a></p>
            <p><a class="btn btn-warning" href="{% url 'catalog:update' object.pk %}" role="button">Изменить &raquo;</a></p>
            <p><a class="btn btn-danger" href="{% url 'catalog:delete' object.pk %}" role="button">Удалить &raquo;</a></p>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
        </div>
    </div>
</div>