catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig

from catalog.views import (display_contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, PostListView, PostDetailView, PostCreateView, PostUpdateView,
                           PostDeleteView)

app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),

    path('contacts/', display_contacts, name='contacts'),

    path('blog/', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/<str:slug>/', PostDetailView.as_view(), name='post'),
    path('post/update/<int:pk>/<str:slug>', PostUpdateView.as_view(), name='update_post'),
    path('post/delete/<int:pk>/<str:slug>', PostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_user, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/<int:user_pk>/', verification_user, name='verification'),
    # path('recovery_password/', PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='recovery_password'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('email',)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.contrib.auth import login
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.services import send_code_email, send_new_password
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        obj = form.save()
        obj.is_active = False
        obj.save()
        send_code_email(obj)
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def verification_user(request, user_pk):
    """Верификация почты, после прохождения по ссылке перенаправляет на личные данные"""
    user = get_object_or_404(User, pk=user_pk)
    user.is_active = True
    user.save()
    login(request, user)
    return redirect(reverse('users:profile'))


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(10)])

    request.user.set_password(new_password)
    request.user.save()
    send_new_password(email=request.user.email, new_password=new_password)
    return redirect(reverse('users:profile'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                    </div>


                    <div class="card-footer">
                        <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

users/templates/users/password_reset_email.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Восстановление пароля
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a href="{% url 'users:generate_password' %}" class="btn btn-success">Отправить новый пароль на почту</a>
                    </div>


                    <div class="card-footer">
                        <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>

        {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Cгенерировать новый пароль</a>

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}