catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig

from catalog.views import (display_contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, PostListView, PostDetailView, PostCreateView, PostUpdateView,
                           PostDeleteView)

app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),

    path('contacts/', display_contacts, name='contacts'),

    path('blog/', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/<str:slug>/', PostDetailView.as_view(), name='post'),
    path('post/update/<int:pk>/<str:slug>', PostUpdateView.as_view(), name='update_post'),
    path('post/delete/<int:pk>/<str:slug>', PostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_user, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/<int:user_pk>/', verification_user, name='verification'),
    # path('recovery_password/', PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='recovery_password'),
    path('profile/generate_new_password/', generate_new_password, name='generate_new_password')
]

catalog/models.py
from django.db import models
from pytils.translit import slugify

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.CharField(max_length=100)
    price = models.IntegerField(verbose_name='цена за покупку')
    date_of_creation = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    date_of_change = models.DateTimeField(verbose_name='дата последнего изменения', auto_now=True)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Кем создан', **NULLABLE)

    def __str__(self):
        return f'{self.title} - {self.price} рублей'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('title',)


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('title',)


class Post(models.Model):
    name = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    published = models.BooleanField(verbose_name='признак публикации', default=True)
    views_count = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.slug is None:
            self.slug = slugify(self.name)

    def __str__(self):
        return f'{self.name} {self.slug}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created_at',)

    def increase_views_count(self):
        """
        Увеличивает просмотры поста на 1.
        """
        self.views_count += 1
        self.save()


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.IntegerField(verbose_name='номер версии')
    title_version = models.CharField(max_length=150, verbose_name='название версии')
    is_active = models.BooleanField(verbose_name='признак текущей версии', default=True)

    def __str__(self):
        return f'{self.title_version} ({self.product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleForMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleForMixin, forms.ModelForm):

    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                       'радар']

    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'category', 'price')

    def clean_title(self):
        clean_title = self.cleaned_data['title']
        for word in self.forbidden_words:
            if word in clean_title.lower():
                raise forms.ValidationError(f'Название не может содержать слово "{word}"')
        return clean_title

    def clean_description(self):
        clean_description = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in clean_description.lower():
                raise forms.ValidationError(f'Описание не может содержать слово "{word}"')
        return clean_description


class VersionForm(StyleForMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Post, Version


class ProductListView(ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


def display_contacts(request):
    return render(request, 'catalog/contacts.html')


class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = Post.objects.filter(published=True)
        return queryset


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        post.increase_views_count()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ('name', 'content', 'image', 'published')
    success_url = reverse_lazy('catalog:post_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.name)
            new_post.save()
            return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ('name', 'content', 'image', 'published')
    # success_url = reverse_lazy('catalog:post_list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.name)
            new_post.save()

            return super().form_valid(form)

    def get_success_url(self):

        return reverse('catalog:post', args=[self.kwargs.get('pk'), self.kwargs.get('slug')])


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('catalog:post_list')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_catalog_menu.html' %}


<main role="main">
    {% block content %}
    {% endblock %}
    <div class="row">
    </div>
</main>

{% include 'catalog/includes/inc_footer.html' %}

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
<!--                    <input type="submit">-->
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/post_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены, что хотите удалить продукт "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:post_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/post_detail.html
{% extends 'catalog/base.html' %}

{% load mediapath %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Заголовок</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>Содержимое</td>
                        <td>{{ object.content }}</td>
                    </tr>
                    <tr>
                        <td>Изображение</td>
                        <td><p><img src="{% mediapath object.image %}" width="150" height="120" alt="Картинка"></p></td>
                    </tr>
                    <tr>
                        <td>Дата публикации</td>
                        <td>{{ object.created_at }}</td>
                    </tr>
                    <tr>
                        <td>Количество просмотров</td>
                        <td>{{ object.views_count }}</td>
                    </tr>

                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:post_list' %}" class="btn btn-primary"><< Назад</a>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/post_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" class="btn btn-success" value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:post_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/post_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Публикации</h1>
</div>

<div class="col-12">
        <a href="{% url 'catalog:create_post' %}" class="btn btn-primary">Создать публикацию</a><br><br>
</div>

<div class="container">
    {% if object_list%}
        <div class="row text-center">
            {% for object in object_list %}
            {% include 'catalog/includes/inc_post_card.html' %}
            {% endfor %}
    </div>
    {% else %}
        <h3>Публикаций нет</h3>
    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены, что хотите удалить продукт "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load mediapath %}
<div class="col">
    <div class="card">
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>Наименование</td>
                    <td>{{ object.title }}</td>
                </tr>
                <tr>
                    <td>Описание</td>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <td>Изображение</td>
                    <td><img src="{% mediapath object.image %}" width="150" height="120" alt="Картинка"></td>
                </tr>
                <tr>
                    <td>Создатель</td>
                    <td>{{ object.created_by|default:"Не указан" }}</td>
                </tr>
                <tr>
                    <td>Цена</td>
                    <td>{{ object.price }}</td>
                </tr>
            </table>
        </div>
        <div class="card-footer">
            <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
            </a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Создание продукта
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:home' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Версии продукта
                    </h3>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="col-12">
        <a href="{% url 'catalog:create' %}" class="btn btn-primary">Создать продукт</a><br><br>
    </div>

    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            {% include 'catalog/includes/inc_product_card.html' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}